apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: unir-containers
  labels:
    app/repo: nodejs-mongodb
spec:
  selector:
    app: nodejs-mongodb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
