apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-configmap
  namespace: unir-containers
  labels:
    app: nodejs-mongodb
    app/repo: nodejs-mongodb
data:
  MONGODB_HOST: mongo-service
  MONGODB_DATABASE: unir
  MONGODB_USER: admin